notifications:
  email: false
language: node_js
node_js:
- node
deploy:
  provider: npm
  email:
    secure: SF6/snp9/QlXqnxbi3G6rlWixsAc2vzXNk1bGIfKQX5z4+tbT5F/EVrMTPFxWXoelwbn+BTEVHR7QXwALHOLiVeLFKs8sFOQQ8O6HAOasaparKVWeYl+XeDfrQhi2e7Xhbq2yor1V8J8Ju7DhJROff54s17DdesgGCDOltmGliIWnZwxm4Bj4Tgd+dlnhfVWMqoZJDgjV34Firl5NW47arSn8Jj9TMqkZ1/YbOIGiHfj1LToqdVY8+e9K7v3kJePX4VV01XUp5UOHoQqMTvk/WRwTYyY+6fE3u6hD4D0V+bBSWOjJNSXnEZc9BBRF+mNCJqIkx0csobH29/Ivrbb5jaLR76Y36jnOpCfRK1/Afvzd0IJ998S3Aa+yYFfS+ggIdzci3U1YaIIocO2UI843iV9riLIKmeoF3vxRJWpIvRTcEISSyyQgu3zTXUcqSG/YSSa/XMwZbuih7ozQ/uAPpujVtS7zHzFhPKsz0L9TvuVyskfNk8t7uzEpp0x0d6Xtrk1+xw5wXoR3C/n/7vCfXzI0Huh5h9DRFZKDXvZEs0+tC0XvKdpW94lHPneZwaXCUAZw7dMObd55cO02Fa6wERHddetr2vtieXsbJLb5F6PeclhSn9qMw6uYW4osikbA+wHrB5eKX9xr6SM/LCpTJJQ2myK+FTS/ADoE+Hcy5A=
  api_key:
    secure: oMxlAVjJm9AOwArXz/DafBSAoHwPphxdqbZ+niAvx4gIOzj3IW5hoKBLKnABVxGVZVaTnISwGVpBKC7a3pKH0VZ2DushEeL5xCJVsb5+Y8U8DKMg47fUeAV0x3veslzz8IGpcErKH6ETJuasJ3LTpg5HIc9N0kdla7I0izm4osv8ovfKGgavCic3vkUwqKkxZnQH5BH4KtMDYedRlTD8F+qgluB2D+jxekFu6chCVNfibcGyzk2x6QvM4cDeFyE66cEKsgRbewABG6E128zbUtQpbFv3TOjPDC7YtQeJgXCecQRkhURj5V8IuYzhd2XyOjzqvz2K9lKjkJoZO1X5bNQEvTDDFJkqmmx+T1eJXxVHH2TH/Iu5pgD6HzRTBIt75qq0up8FG5BFMq0KsUQyjVPdRtmnLq3oD9pMRTB20O8LTfIFmUgyT3rHFYljOuc+jChQKKAajOaWHRytCQd+FqCArtJHB3q/Ml9IoaEASl2jcureJElnQn54kg9jxbXcHdz7aii5KkU7MrSwW99l6yll/Cdvsmnc6vMbZNc2cfesWpo2042994L3299npeZ6q07q0+L7OWsDbjvlQ+AqzUrIuZ+tu1QL3CCwPI2NChNa7E6trtMHQQbiVy73Gylfbn3Qu70dcSlvcmDLtYTgjUjCDmH8yIXjraL9FFsiYQc=
  on:
    tags: true
